[theme]
primaryColor = "#087f8c"
backgroundColor = "#f5f7fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#172b4d"
font = "sans serif"

[client]
showErrorDetails = "none"
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[server]
headless = true
enableStaticServing = true
